"""
Django settings for medBot project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i-7f%k^0k&14$p8)w1n)nra_l8fij*a7lllz8zw$fr*9q*spmu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# settings.py
# OPENAI_API_KEY = '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'
# OPENAI_API_KEY = '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'
OPENAI_API_KEY ='AIzaSyDT23jL93xPJC6BRdONk1kR_p_5kKAoIh4' 
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',  # Add your app here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medBot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'authentication', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medBot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# import firebase_admin
# from firebase_admin import credentials

# # Path to your Firebase service account key
# FIREBASE_CREDENTIALS = "path/to/serviceAccountKey.json"

# # Initialize Firebase Admin SDK
# firebase_cred = credentials.Certificate(FIREBASE_CREDENTIALS)
# firebase_admin.initialize_app(firebase_cred)

# # Email Settings for Django
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.elasticemail.com'  # or your SMTP server
# EMAIL_PORT = 2525
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'mollasheryfawaz@gmail.com'
# EMAIL_HOST_PASSWORD = '@fawaz@123'


import os

STATIC_URL = '/static/'

STATICFILES_DIRS = [    
    os.path.join(BASE_DIR, 'authentication', 'static'),
 ]

LOGIN_REDIRECT_URL = "home"  # Redirect to home page after login
LOGOUT_REDIRECT_URL = "signin"  # Redirect to signin after logout





